services:
  - type: web
    name: kwielove-discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
